#! /usr/bin/ruby
require 'rubygems'
require 'jabs'
require 'sass'
require 'sass/plugin'
require 'haml'
require 'continuous_builder'
require 'pathname'
require 'ruby2ruby'

$-w = nil
$-v = nil

class Pathname
  alias / +
  alias old_initialize initialize
  def initialize path
    old_initialize(path.to_s)
  end
end

$dir = Pathname.new(__FILE__).dirname

class GistLiveContinuousBuilder < ContinuousBuilder
  watches :jabs,
    :files => "./src/**/*.js.jabs",
    :module => Jabs,
    :update => :repack
  
  watches :haml,
    :files => "./src/**/*.html.haml",
    :module => Haml,
    :update => :repack

  watches :public_haml,
    :files => "./public/**/*.html.haml",
    :module => Haml

  watches :public_sass,
    :files => "./public/**/*.css.sass",
    :module => Sass

  watches :edit_area_source,
    :files => "./public/edit_area/*.js",
    :update => :repack

  watches :legs,
    :files => "./public/legs.js",
    :update => :repack

  def pack
    pack = []
    pack << ($dir/'vendor'/'jquery-1.2.6.min.js').read
    pack << ($dir/'vendor'/'json2.js').read
    pack
  end

  def repack_mod mod, &block
    mod_pack = pack
    
    Pathname.glob($dir/'src'/mod/'*.html').each do |path|
      script = "var #{path.basename.to_s.gsub('.html', '')}" 
      script << "= jQuery(\"#{path.read.gsub("\n", '')}\");"
      mod_pack << script 
    end

    specifics = []
    specifics.instance_eval &block
    specifics.each do |script| 
      mod_pack << ($dir/script).read
    end    
        
    path = $dir/'public'/"#{mod}.js"
    f= File.open(path, 'w')
    f.write(mod_pack.join(";\n\n"))
    f.close
  end

  def repack path
    repack_mod :embedded do
      push 'vendor/jquery.center.js'
      push 'vendor/jquery.corner.js'
      push 'vendor/gradient-1.0/jquery.gradient.pack.js'
      push 'src/embedded/gist_live.js'
    end
    
    repack_mod :editor do
      push  'vendor/diff_match_patch/diff_match_patch.js'
  # Needs to load files as it goes    
      push  'public/edit_area/edit_area_full.js'
      push  'vendor/Orbited.js'
      push  'public/legs.js'
    end
  end
end

builder = GistLiveContinuousBuilder.new
builder.build_all
builder.build_continuously
